### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by stoyanovd** [mastahyeti/Google-Docs-Markdown#3]
My google doc consists only from nested lists.

Linebreaks after item are ignored and no lists are generated.

**Comment by btoews** [comment]
My guess is that when typing the list in Google Docs, you're Markdown list is getting turned into rich text bullet points by Docs. I created a document with an actual Markdown list:

```
- test
- test
  - test
  - test
    - test
  - test
- test 
```

and it seems to render fine:

<img width="599" alt="screen shot 2015-10-07 at 11 33 43 am" src="https://cloud.githubusercontent.com/assets/1144197/10345510/746ae348-6ce7-11e5-8738-30a4d08a0883.png">

I'm going to close this issue. Let me know if I'm misunderstanding the problem and I'lll reopen it.

**Comment by stoyanovd** [comment]
Sorry, I not understood it's purpose. I thought it will convert google docs'style text to markdown style.
Now all become clear. Maybe I will not overlook readme so fast next time...

Thanks for fast reply.

**Comment by btoews** [comment]
> Sorry, I not understood it's purpose. I thought it will convert google docs'style text to markdown style.
> Now all become clear. Maybe I will not overlook readme so fast next time...

Yep. It converts Markdown formatted plain text into HTML.

> Thanks for fast reply.

No problem :smile:
